version: '3.8'
services:
  dev-db-cache:
    image: redis:7-alpine
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./cache:/data

  test-db-cache:
    image: redis:7-alpine
    restart: always
    ports:
      - ${REDIS_PORT}:6379

volumes:
  cache:
    driver: local
